spring:
  application:
    name: book-api

  datasource:
    url: jdbc:postgresql://localhost:5432/book_db
    username: postgres
    password: "Monponki24?"
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: localhost
    port: 9999
    properties:
      mail:
        smtp:
          auth: false

  security:
    recaptcha:
      secret: your_recaptcha_secret_key
      site: your_recaptcha_site_key

# Уровень приложения (без отступа)
app:
  upload:
    dir: uploads
  html:
    dir: html-books

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /api-docs/swagger-config
    url: /api-docs
    operations-sorter: method
    tags-sorter: alpha

jwt:
  secret: your-secret-key-change-in-production-minimum-256-bits-long-key-here
  expiration: 86400000